GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vZXIiLCJpYXQiOjE2ODg5OTkyMjUsImV4cCI6MTY4ODk5OTI0MH0.-BLJRQ3kCPktRUL6gLcw-QdeJMtQiK56yohP4c-HZsU
###
POST http://localhost:3000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.bW9lcg.-M9-ytCMTTxo6ntv8J94NPW_OvrR62k4FZgjGPekb-c"
}
### 
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "moer"
}

### 
DELETE  http://localhost:3000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.bW9lcg.-M9-ytCMTTxo6ntv8J94NPW_OvrR62k4FZgjGPekb-c"
}